---

installation_drive:
  name: "{{ lookup('community.general.bitwarden', 'host_vars_bm-2', field='installation_drive.name') | join }}"
  efi_partition_suffix: -part1
  efi_partition_label: efi
  root_partition_suffix: -part2
  root_zpool: arch

hostname: bm-2
gpu_manufacturer: intel
# en_PL, pl_PL
system_language: en_PL
kvm_enabled: true
installation_secure_boot_enabled: false
installation_uki_enabled: false

installation_kernel_cmdline: intel_iommu=on iommu=pt

network_bond_enabled: true
network_bond_slaves:
  - eno1
  - eno2
  - eno3
  - eno4
network_interface: bond0
network_config:
  connection_name: "Wired connection 1"
  ipv4: 192.168.100.52/24
  gw4: 192.168.100.1
  dns4: 192.168.100.1
  dns4_search: "{{ localdomain }}"

zfs_additional_drives_enabled: true
zfs_zpools:
  - name: nvme2
    encryption: false
    compression: "off"
    datasets:
      - name: vm-nvme
    devices:
      - "{{ lookup('community.general.bitwarden', 'host_vars_bm-2', field='zfs_devices_nvme_2') | first }}"
