---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: solar-creeper
  namespace: solar-creeper
spec:
  chart:
    spec:
      chart: solar-creeper
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: solar-creeper
  valuesFrom:
  - kind: ConfigMap
    name: solar-creeper-values
    valuesKey: values.yaml
